change pip to v19.0.3 and libffi to v3.2

diff --git a/packages/python/packaging b/packages/python/packaging
--- a/packages/python/packaging
+++ b/packages/python/packaging
@@ -6,14 +6,14 @@ set -u
 # We grab the latest versions that are in the directory
 PYTHON_VERSION=`ls -r python/Python-*.tar.xz | sed 's/python\/Python-\(.*\)\.tar\.xz/\1/' | head -1`
 
-echo "Extracting libffi-3.4.2.tar.gz ..."
-if ! tar xpvf python/libffi-3.4.2.tar.gz ; then
-  echo "Failed extracting libffi-3.4.2.tar.gz ..."
+echo "Extracting libffi-3.2.tar.gz ..."
+if ! tar xpvf python/libffi-3.2.tar.gz ; then
+  echo "Failed extracting libffi-3.2.tar.gz ..."
   exit 1
 fi
 
 echo "Installing libffi..."
-pushd libffi-3.4.2
+pushd libffi-3.2
   ./configure --prefix="${BOSH_INSTALL_TARGET}"/libffi
   make
   make install
